name: common

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: "@dr4g0nb4ll2"
      MYSQL_DATABASE: tour_operations

    ports:
      - "3306:3306"

    volumes:
      - common_mysql:/var/lib/mysql

volumes:
  common_mysql: